---
title: "Widget Production - Partial Solution"
output: html_notebook
---

## Problem Statement  

A company has to decide its production levels for the next 2 quarters. The anticipated widget demand for those months are 1000, 1400, 1700, 1500, 1800, and 1200 units respectively. The maximum production per month is 1400 units. Widgets produced one month can be delivered either that same month or stored in inventory and delivered at some other month. It costs the company \$3 to produce a widget in standard production and \$2 to carry one unit in inventory from one month to the next. Through additional man-hours, up to 500 additional units can be produced per month but, in this case, the company incurs an additional cost of $7/unit. Formulate as a linear program the problem of determining the production levels so as to minimize the total costs.

#### Decision variables: 

$p_i$ : amount produced each month (under 1400)  
$o_i$ : monthly overtime production (under 500)

**Slack Variables:**  
$s_i$ : leftover stock each month  

#### Objective Function:

Min $z = \sum_{i=1}^{6}3s_i+7o_i+2p_i$

#### Constraints

$d_i$ : the required demand each month

$s_{i-1}+p_i+o_i-s_i = d_i$

* **Q:** Why is this an equality and not an inequality like previous examples we discussed?

$s_i,p_i,o_i \geq 0$